### ISSUE TITLE
WEBAPI is down for server change.

### ISSUE THREAD

**Issue by AnnsAnns** [tumGER/BETCH#23]
As I transition this to a local server, the API and discord bot is currently down for the first time in nearly a year.

**Comment by gabehxd** [comment]
👏 👏 🎉

**Comment by AnnsAnns** [comment]
The server transfer is complete. The service is now running purely through err.tomger.eu.

All requests made at err.teamatlasnx.com and betch.tomger.eu are also transferred through that domain. Besides that, this is now running on a reverse proxy.

I'll monitor the stability throughout the day but it seems to run fine.
